#!/usr/bin/env bash

#[*] Name of the script: MetaExif
#[*] Description: "Extract Metadata from an Image"
#[*] Version: 1.0
#[*] Author: JRIC2002
#[*] Date of creation: 02/05/2019
#[*] Date of last update: 30/04/2020

#COLORS
black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
magenta='\033[1;35m'
cyan='\033[1;36m'
white='\033[0m'

#BANNER

function banner {
	
	printf "
	    $green __  __      _       $yellow _____      _  __
	    $green|  \/  | ___| |_ __ _$yellow| ____|_  _(_)/ _|
	    $green| |\/| |/ _ \ __/ _' $yellow|  _| \ \/ / | |_
	    $green| |  | |  __/ || (_| $yellow| |___ >  <| |  _|
	    $green|_|  |_|\___|\__\__,_$yellow|_____/_/\_\_|_|  $white v1.0

	      $green.:.:.$blue Script encoded by:$white @JRIC2002 $green.:.:.$white
      $green.:.:.$blue Description:$white Extract Metadata from an Image  $green.:.:.$white
	"

}

#EXTRAER METADATOS

function metadatos {
	
	echo ""
	printf "$cyan File Path:$white"
	read -p " " ruta_archivo

	if [ -e $ruta_archivo  ]; then
		echo ""
		printf "$green[$white*$green]$black Extracting Metadata from the File ....\n$white"
		echo ""
		sleep 3
		exiv2 pr $ruta_archivo
	else
		echo ""
		printf "$red[$white*$red] The File or Directory does Not Exist\n$white"
		echo ""
	fi

}

#FUNCIONES

banner
metadatos

